namespace EFS_Professional
{
    using System;

    public class Qcdm
    {
        public enum Cmd : short
        {
            DIAG_AKEY_VERIFY_F = 90,
            DIAG_BAD_CMD_F = 0x13,
            DIAG_BAD_LEN_F = 0x15,
            DIAG_BAD_MODE_F = 0x18,
            DIAG_BAD_PARM_F = 20,
            DIAG_BAD_SEC_MODE_F = 0x47,
            DIAG_BAD_SPC_MODE_F = 0x42,
            DIAG_BMP_HS_SCREEN_F = 0x5b,
            DIAG_CONFIG_COMM_F = 0x5c,
            DIAG_CONTROL_F = 0x29,
            DIAG_CPU_RW_F = 90,
            DIAG_DIAG_VER_F = 0x1c,
            DIAG_DLOAD_F = 0x3a,
            DIAG_END_F = 0x36,
            DIAG_ERR_CLEAR_F = 0x2b,
            DIAG_ERR_READ_F = 0x2a,
            DIAG_ESN_F = 1,
            DIAG_EVENT_REPORT_F = 0x60,
            DIAG_EXT_BUILD_ID_F = 0x7c,
            DIAG_EXT_LOGMASK_F = 0x5d,
            DIAG_FEATURE_QUERY_F = 0x51,
            DIAG_FS_OP_F = 0x59,
            DIAG_GET_DIPSW_F = 0x2f,
            DIAG_GET_GUID_F = 0x67,
            DIAG_GET_PERM_PROPERTY_F = 0x69,
            DIAG_GET_PROPERTY_F = 0x65,
            DIAG_GPS_GRID_F = 0x6d,
            DIAG_GPS_SESS_CTRL_F = 0x6c,
            DIAG_GPS_STATISTICS_F = 110,
            DIAG_HS_KEY_F = 0x20,
            DIAG_HS_LOCK_F = 0x21,
            DIAG_HS_SCREEN_F = 0x22,
            DIAG_INP_F = 10,
            DIAG_INPW_F = 11,
            DIAG_LOG_F = 0x10,
            DIAG_LOGMASK_F = 15,
            DIAG_MARKOV_F = 0x1a,
            DIAG_MARKOV_RESET_F = 0x1b,
            DIAG_MAX_F = 0x70,
            DIAG_MSG_F = 0x1f,
            DIAG_NV_PEEK_F = 0x11,
            DIAG_NV_POKE_F = 0x12,
            DIAG_NV_READ_F = 0x26,
            DIAG_NV_WRITE_F = 0x27,
            DIAG_ORIG_F = 0x35,
            DIAG_OUTP_F = 8,
            DIAG_OUTPW_F = 9,
            DIAG_PARM_GET_IS95B_F = 0x58,
            DIAG_PARM_GET2_F = 0x43,
            DIAG_PARM_RETRIEVE_F = 0x62,
            DIAG_PARM_SET_F = 0x24,
            DIAG_PASSWORD_F = 70,
            DIAG_PEEKB_F = 2,
            DIAG_PEEKD_F = 4,
            DIAG_PEEKW_F = 3,
            DIAG_PERM_USER_CMD_F = 0x6b,
            DIAG_PILOT_SETS_F = 0x40,
            DIAG_POKEB_F = 5,
            DIAG_POKED_F = 7,
            DIAG_POKEW_F = 6,
            DIAG_PR_LIST_RD_F = 0x49,
            DIAG_PR_LIST_WR_F = 0x48,
            DIAG_PUT_PERM_PROPERTY_F = 0x6a,
            DIAG_PUT_PROPERTY_F = 0x66,
            DIAG_RAM_RW_F = 0x59,
            DIAG_RPC_F = 100,
            DIAG_SER_REPORT_F = 0x2d,
            DIAG_SER_RESET_F = 0x2c,
            DIAG_SERIAL_CHG_F = 0x44,
            DIAG_SET_DIPSW_F = 0x30,
            DIAG_SET_FTM_TEST_MODE = 0x72,
            DIAG_SET_MAX_SUP_CH_F = 0x57,
            DIAG_SMS_READ_F = 0x53,
            DIAG_SMS_WRITE_F = 0x54,
            DIAG_SPC_F = 0x41,
            DIAG_STATE_F = 0x3f,
            DIAG_STATUS_F = 12,
            DIAG_STATUS_SNAPSHOT_F = 0x63,
            DIAG_STREAMING_CONFIG_F = 0x61,
            DIAG_SUBSYS_CMD_F = 0x4b,
            DIAG_SUP_FER_F = 0x55,
            DIAG_SUP_WALSH_CODES_F = 0x56,
            DIAG_SW_VERSION_F = 0x38,
            DIAG_TA_PARM_F = 30,
            DIAG_TAGRAPH_F = 0x19,
            DIAG_TEST_F = 0x2e,
            DIAG_TMOB_F = 0x3b,
            DIAG_TS_F = 0x1d,
            DIAG_TUNNEL_F = 0x6f,
            DIAG_USER_CMD_F = 0x68,
            DIAG_VERNO_F = 0,
            DIAG_VOC_PCM_LB_F = 0x31,
            DIAG_VOC_PKT_LB_F = 50,
            NOT_A_COMMAND = -1222
        }

        public enum Diag_Response : short
        {
            DIAG_ERR_BAD_CMD = 2,
            DIAG_ERR_BAD_LENGTH = 4,
            DIAG_ERR_BAD_MODE = 0x20,
            DIAG_ERR_BAD_PARAM = 3,
            DIAG_ERR_BAD_REPLY_CMD = 11,
            DIAG_ERR_BAD_SECURITY_MODE = 5,
            DIAG_ERR_BAD_SPC_MODE = 0x15,
            DIAG_ERR_FAIL = 1,
            DIAG_ERR_SUCCESS = 0,
            DIAG_ERR_UNKNOWN = 0xff
        }

        public enum diagpkt_subsys_cmd_enum_type : short
        {
            DIAG_SUBSYS_ANALOG = 0x42,
            DIAG_SUBSYS_APIONE_PROGRAM = 0x38,
            DIAG_SUBSYS_APIONE_PROGRAM_MODEM = 0x43,
            DIAG_SUBSYS_APPS = 0x1f,
            DIAG_SUBSYS_APR = 0x4e,
            DIAG_SUBSYS_AUDIO_SETTINGS = 0x11,
            DIAG_SUBSYS_AUTOCONFIG = 0x31,
            DIAG_SUBSYS_BREW = 0x45,
            DIAG_SUBSYS_BT = 3,
            DIAG_SUBSYS_CALLP1X = 30,
            DIAG_SUBSYS_CHORD = 0x47,
            DIAG_SUBSYS_CLKRGM = 0x27,
            DIAG_SUBSYS_CM = 15,
            DIAG_SUBSYS_CNV = 0x37,
            DIAG_SUBSYS_COREBSP = 0x4b,
            DIAG_SUBSYS_DATA1X = 0x1c,
            DIAG_SUBSYS_DEBUG = 0x25,
            DIAG_SUBSYS_DEVICES = 40,
            DIAG_SUBSYS_DIABLO = 6,
            DIAG_SUBSYS_DIAG_SERV = 0x12,
            DIAG_SUBSYS_DM = 0x3b,
            DIAG_SUBSYS_DRM = 0x3a,
            DIAG_SUBSYS_DS_ATCOP = 0x34,
            DIAG_SUBSYS_DTV = 0x2c,
            DIAG_SUBSYS_FC = 60,
            DIAG_SUBSYS_FLUTE = 0x41,
            DIAG_SUBSYS_FS = 0x13,
            DIAG_SUBSYS_FS_ALTERNATE = 0x3e,
            DIAG_SUBSYS_FTM = 11,
            DIAG_SUBSYS_GPS = 13,
            DIAG_SUBSYS_GSDI = 0x21,
            DIAG_SUBSYS_GSM = 8,
            DIAG_SUBSYS_GUNIMON = 0x18,
            DIAG_SUBSYS_HDR = 5,
            DIAG_SUBSYS_HIT = 0x39,
            DIAG_SUBSYS_HS = 0x10,
            DIAG_SUBSYS_HWTC = 10,
            DIAG_SUBSYS_L4LINUX = 0x35,
            DIAG_SUBSYS_LAST = 0x54,
            DIAG_SUBSYS_LEGACY = 0xff,
            DIAG_SUBSYS_LSM = 0x19,
            DIAG_SUBSYS_LTE = 0x44,
            DIAG_SUBSYS_MDDI = 0x33,
            DIAG_SUBSYS_MEDIAPLAYER = 0x15,
            DIAG_SUBSYS_MEMORY = 0x3d,
            DIAG_SUBSYS_MFLO = 0x2b,
            DIAG_SUBSYS_MFLO2 = 0x4c,
            DIAG_SUBSYS_MOBIMON = 0x17,
            DIAG_SUBSYS_MUX1X = 0x1b,
            DIAG_SUBSYS_MVS = 0x36,
            DIAG_SUBSYS_NV = 0x30,
            DIAG_SUBSYS_OEM = 0,
            DIAG_SUBSYS_OEMDPP = 0x51,
            DIAG_SUBSYS_OS = 12,
            DIAG_SUBSYS_PARAMS = 50,
            DIAG_SUBSYS_PM = 0x24,
            DIAG_SUBSYS_PORT_MAP_SETTINGS = 20,
            DIAG_SUBSYS_PROF = 0x2e,
            DIAG_SUBSYS_PS = 0x2a,
            DIAG_SUBSYS_PS_DATA_LOGGING = 0x2a,
            DIAG_SUBSYS_PWRDB = 70,
            DIAG_SUBSYS_Q5_CORE = 0x52,
            DIAG_SUBSYS_Q6_CORE = 0x4a,
            DIAG_SUBSYS_QCAMCORDER = 0x1a,
            DIAG_SUBSYS_QCAMERA = 0x16,
            DIAG_SUBSYS_QNP = 0x4f,
            DIAG_SUBSYS_QTV = 0x26,
            DIAG_SUBSYS_REGRESSION = 0x3f,
            DIAG_SUBSYS_RESERVED_OEM_0 = 250,
            DIAG_SUBSYS_RESERVED_OEM_1 = 0xfb,
            DIAG_SUBSYS_RESERVED_OEM_2 = 0xfc,
            DIAG_SUBSYS_RESERVED_OEM_3 = 0xfd,
            DIAG_SUBSYS_RESERVED_OEM_4 = 0xfe,
            DIAG_SUBSYS_REX = 12,
            DIAG_SUBSYS_RRC = 0x2d,
            DIAG_SUBSYS_SD = 2,
            DIAG_SUBSYS_SEC = 0x48,
            DIAG_SUBSYS_SENSORS = 0x40,
            DIAG_SUBSYS_SETTINGS = 0x20,
            DIAG_SUBSYS_SRCH1X = 0x1d,
            DIAG_SUBSYS_STRIDE = 80,
            DIAG_SUBSYS_TCXOMGR = 0x2f,
            DIAG_SUBSYS_TIME = 0x49,
            DIAG_SUBSYS_TMC = 0x22,
            DIAG_SUBSYS_TREX = 7,
            DIAG_SUBSYS_UIMDIAG = 0x21,
            DIAG_SUBSYS_ULOG = 0x4d,
            DIAG_SUBSYS_UMTS = 9,
            DIAG_SUBSYS_USB = 0x23,
            DIAG_SUBSYS_USCRIPT = 0x53,
            DIAG_SUBSYS_WCDMA = 4,
            DIAG_SUBSYS_WLAN = 0x29,
            DIAG_SUBSYS_WMS = 14,
            DIAG_SUBSYS_ZREX = 1
        }

        public enum FSItems : short
        {
            BASE = 0
        }

        public enum Mode : short
        {
            MODE_RADIO_LOWPOWER = 5,
            MODE_RADIO_OFFLINE_ANALOG = 0,
            MODE_RADIO_OFFLINE_DIGITAL = 1,
            MODE_RADIO_OFFLINE_FACTORY_TEST = 3,
            MODE_RADIO_ONLINE = 4,
            MODE_RADIO_POWER_OFF = 6,
            MODE_RADIO_RESET = 2
        }

        public enum NV_Response : short
        {
            NV_ERR_BAD_PARAM = 6,
            NV_ERR_BAD_SECURITY_MODE = 20,
            NV_ERR_FAIL = 1,
            NV_ERR_INACTIVE_NV_ITEM = 5,
            NV_ERR_READ_ONLY_NV_ITEM = 7,
            NV_ERR_SUCCESS = 0,
            NV_ERR_UNKNOWN = 0xff
        }

        public enum SubsysCmd : short
        {
            CM = 15,
            CONTROL = 250,
            GPS = 13,
            HDR = 5,
            LAST_SUBSYS = 0xfb,
            OLD_CONTROL = 50,
            SMS = 14,
            STORAGE = 0x13
        }

        public enum SubsysStorage : short
        {
            DIAG_EFS2_CLOSE = 3,
            DIAG_EFS2_CLOSEDIR = 13,
            DIAG_EFS2_OPEN = 2,
            DIAG_EFS2_OPENDIR = 11,
            DIAG_EFS2_READ = 4,
            DIAG_EFS2_READDIR = 12,
            DIAG_EFS2_UNLINK = 8,
            DIAG_EFS2_WRITE = 5
        }
    }
}

